version: 1.0.{build}
image: Previous Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
shallow_clone: true
build:
  project: Engine.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd bin_%PLATFORM%


    md ..\Game\Resources_SoC_1.0006\bin_%PLATFORM%


    copy *.* ..\Game\Resources_SoC_1.0006\bin_%PLATFORM%


    cd ..\Game\Resources_SoC_1.0006


    7z a ..\..\OGSR_Engine_SHOC_EDITION_%PLATFORM%_%APPVEYOR_BUILD_VERSION%.7z .\


    cd ..\..\


    appveyor PushArtifact OGSR_Engine_SHOC_EDITION_%PLATFORM%_%APPVEYOR_BUILD_VERSION%.7z %CONFIGURATION%
artifacts:
- path: .\OGSR_Engine_SHOC_EDITION_$(platform)_$(appveyor_build_version).7z
  name: $(configuration)
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: fCUuoKt+E+BdDL+sDGj7wROcLX7DNPC8jXazUC52F3HerLnlIrHKv/pTr7OURHaC
  repository: OGSR/OGSR-Engine
  artifact: Release
  force_update: true
  on:
    appveyor_repo_tag: true
    platform: x64