name: Main Workflow

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[ci build]') || github.event_name == 'release'"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug, Release, ReleaseTracyProfiler]
        Platform: [x64]
        include:
          - Configuration: Debug
            ConfigurationReal: Debug
          - Configuration: Release
            ConfigurationReal: Release
          - Configuration: ReleaseTracyProfiler
            ConfigurationReal: Release
    steps:
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0

    - name: Update Components
      run: |
        ${{ github.workspace }}/Update_Components.cmd

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: MSBuild
      shell: cmd
      run: |
        set APPVEYOR_BUILD_VERSION=3.${{ github.run_number }}
        set APPVEYOR_REPO_NAME=${{ github.repository }}
        set CONFIGURATION_GA=${{ matrix.Configuration }}
        
        msbuild Engine.sln /t:Rebuild /p:Configuration=${{ matrix.ConfigurationReal }} /p:Platform=${{ matrix.Platform }}
    - name: Prepare artifacts
      shell: cmd
      run: |
        set APPVEYOR_BUILD_VERSION=3.${{ github.run_number }}
        set CONFIGURATION=${{ matrix.Configuration }}
        set PLATFORM=${{ matrix.Platform }}
        set OGSR_ARTIFACT_NAME=OGSR_Engine_SHOC_EDITION_%PLATFORM%_%APPVEYOR_BUILD_VERSION%_%CONFIGURATION%.7z
        cd bin_%PLATFORM%
        
        md ..\Game\Resources_SoC_1.0006\bin_%PLATFORM%
        
        del *.ico
        
        copy *.* ..\Game\Resources_SoC_1.0006\bin_%PLATFORM%
        
        cd ..\Game\Resources_SoC_1.0006
        
        7z a -t7z -m0=LZMA2:d=96m:fb=273 -mx=9 -mmt=2 ..\..\%OGSR_ARTIFACT_NAME% .\
    - name: Upload OGSR artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: OGSR_Engine_SHOC_EDITION_${{ matrix.Platform }}_3.${{ github.run_number }}_${{ matrix.Configuration }}.7z
        path: .\OGSR_Engine_SHOC_EDITION_${{ matrix.Platform }}_3.${{ github.run_number }}_${{ matrix.Configuration }}.7z

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: Czuz/upload-release-asset@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .\OGSR_Engine_SHOC_EDITION_${{ matrix.Platform }}_3.${{ github.run_number }}_${{ matrix.Configuration }}.7z
        asset_name: OGSR_Engine_SHOC_EDITION_${{ matrix.Platform }}_3.${{ github.run_number }}_${{ matrix.Configuration }}.7z
        asset_content_type: application/zip
